# Generated by Django 2.1.5 on 2019-01-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clustername', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'VMCluster',
            },
        ),
        migrations.CreateModel(
            name='VMDatacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacentername', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'VMDatacenter',
            },
        ),
        migrations.CreateModel(
            name='VMHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=250)),
                ('clustername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMCluster')),
                ('datacentername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMDatacenter')),
            ],
            options={
                'db_table': 'VMHost',
            },
        ),
        migrations.CreateModel(
            name='VMVirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmname', models.CharField(max_length=500)),
                ('istemplate', models.BooleanField(default=True)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMHost')),
                ('clustername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMCluster')),
                ('datacentername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMDatacenter')),
            ],
            options={
                'db_table': 'VMVirtual',
            },
        ),
        migrations.AddField(
            model_name='vmcluster',
            name='datacentername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMDatacenter'),
        ),
    ]
