# Generated by Django 2.1.5 on 2019-01-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VMwareAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmhost',
            name='clustername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMCluster'),
        ),
        migrations.AlterField(
            model_name='vmvirtual',
            name='clustername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMCluster'),
        ),
        migrations.AlterField(
            model_name='vmvirtual',
            name='hostname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VMwareAPI.VMHost'),
        ),
    ]
