# Generated by Django 2.1.5 on 2019-02-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMwareAPI', '0002_auto_20190117_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmvirtual',
            name='vmstatus',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
