# Generated by Django 2.1.5 on 2019-02-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMwareAPI', '0005_datastore_freespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='freespace',
            field=models.FloatField(null=True),
        ),
    ]
