# Generated by Django 2.1.3 on 2018-11-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntitle', models.CharField(max_length=60)),
                ('ncontent', models.TextField()),
                ('npub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='ntype',
            field=models.ManyToManyField(to='newstest.TypeInfo'),
        ),
    ]
