# Generated by Django 2.1.3 on 2018-11-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsinfo',
            table='NewsInfo',
        ),
        migrations.AlterModelTable(
            name='typeinfo',
            table='TypeInfo',
        ),
    ]
