# Generated by Django 2.1.3 on 2018-11-29 03:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_areainfo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name='areainfo',
            table='AreaInfo',
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table='BookInfo',
        ),
        migrations.AlterModelTable(
            name='heroinfo',
            table='HeroInfo',
        ),
    ]
